Add debugging context
frontkom/common-behat-definitions pull request #8
Opened 2024-08-12 12:29 UTC by adamsokolowski06

**References** 
AKA-71

### Changed 
This context provides 2 things:
- New way of dumping the logs after failed step - I cannot find a thread, but the previous step definition was somehow problematic after upgrade to D10 so we decided to implement the new way
- Deleting the logs after scenario - The most benefit from it is that if a scenario fails you see logs related only to that one scenario, so the old logs won't be misleading and the output is more clear

### Visuals 
None

### How can this be validated? 
1. Use the DebuggingContext in behat config file
2. Prepare a test using some of these steps
3. Run behat tests

### Pull request checklist
- [x] Can be deploy automatically? _If manual actions are required:_ did you describe the deploy steps?
- [x] Is the documentation updated, if it makes sense? 
- [x] Are necessary translations added/updated? 
- [x] Did you update sanitization routines, where personal information is handled?

2024-08-12 13:05 UTC, eiriksm requested changes

2024-08-12 13:05 UTC, eiriksm commented on src/DebuggingContext.php
> +      $query = \Drupal::database()
Hm, maybe we should either try/catch or make sure this table exists first?

Also. I am really sorry I did not notice this before. but Drupal specifics are being placed here: https://github.com/frontkom/drupal-behat-definitions

The reasoning being that some things (like waiting for an element to be visible, or failing on JS errors) is framework agnostic, and can be used in behat tests for wordpress or even next.js if you wanted to

2024-08-12 13:05 UTC, eiriksm commented on src/DebuggingContext.php
> +    $query = \Drupal::database()
I some time find valuable info from the last scenario i feel. For example something failed in the last scenario that affected the current one. Could we at least make it configurable?

2024-08-14 15:02 UTC, closed without merging

2024-08-14 15:03 UTC, adamsokolowski06 commented
I'll create a separate PR with the feedback addressed :slightly_smiling_face: